local opt = vim.o
opt.autowrite = true
opt.number = true
opt.relativenumber = true
opt.showmode = false
opt.clipboard = 'unnamedplus'
opt.wrap = false
opt.smartindent = true
opt.breakindent = true
opt.undofile = true
opt.ignorecase = true
opt.smartcase = true
opt.updatetime = 1000
opt.timeoutlen = 300
opt.splitright = true
opt.splitbelow = true
opt.list = true
opt.inccommand = 'nosplit'
opt.cursorline = true
opt.scrolloff = 10
opt.confirm = true
opt.numberwidth = 2
opt.wildignorecase = true
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.iskeyword:append "-"
vim.g.mapleader = ' '
opt.shiftwidth = 2
